import type {
  AIData,
  ActivitiesData,
  ActivityDetail,
  DashboardData,
  GearData,
  GoalFormInput,
  GoalsData,
  GoalType,
  ProfileData,
  StravaConnectionData,
} from "./types";

export const dashboardFixture: DashboardData = {
  greeting: "Good morning",
  runnerName: "Ram",
  syncLabel: "Strava synced 12 min ago",
  currentDateLabel: "Thursday, September 10",
  summary: [
    {
      label: "Weekly distance",
      value: "28.4 km",
      detail: "+12% from last week",
      icon: "route",
      tone: "primary",
    },
    {
      label: "Runs logged",
      value: "4",
      detail: "3 easy, 1 quality",
      icon: "directions_run",
      tone: "accent",
    },
    {
      label: "Average pace",
      value: "5:08/km",
      detail: "Stable across tempo work",
      icon: "speed",
      tone: "accent",
    },
    {
      label: "Current streak",
      value: "4 days",
      detail: "Recovery day planned tomorrow",
      icon: "local_fire_department",
      tone: "warning",
    },
  ],
  weeklyTotalKm: 28.4,
  weeklyDelta: "+8% from last week",
  weeklyMileage: [
    { day: "Mon", distanceKm: 8.2 },
    { day: "Tue", distanceKm: 6 },
    { day: "Wed", distanceKm: 0 },
    { day: "Thu", distanceKm: 8.2 },
    { day: "Fri", distanceKm: 0, planned: true },
    { day: "Sat", distanceKm: 6, planned: true },
    { day: "Sun", distanceKm: 0, planned: true },
  ],
  recentActivities: [],
  activeGoal: {
    id: "goal-half-oct",
    type: "Half Marathon",
    title: "Autumn Half Marathon",
    targetLabel: "21.1 km on Oct 26",
    currentLabel: "14.6 km longest long run",
    progressPercent: 69,
    remainingLabel: "6.5 km to race distance",
    targetDate: "Oct 26",
    status: "active",
    priority: "A-priority",
  },
  featuredGear: {
    id: "gear-pegasus",
    type: "running-shoes",
    categoryLabel: "Running shoes",
    brand: "Nike",
    model: "Pegasus 41",
    name: "Nike Pegasus 41",
    mileageKm: 487,
    targetMileageKm: 700,
    statusLabel: "Approaching replacement",
    notes: "Daily trainer rotated across road and light trail sessions.",
  },
  aiPrompt:
    "Ask AI Buddy for a breakdown of why your threshold pace improved this week.",
};

export const activitiesFixture: ActivitiesData = {
  filters: ["run", "walk", "cycling", "hiking"],
  activities: [
    {
      id: "activity-intervals",
      title: "Sunset Interval Workout",
      type: "run",
      label: "Quality",
      dateLabel: "Yesterday · 6:42 PM",
      location: "Track and Promenade",
      distanceKm: 10.4,
      duration: "51:12",
      pace: "4:55/km",
      heartRate: 162,
      elevationM: 84,
      cadenceSpm: 176,
      calories: 711,
      weather: "Clear · 18 C",
      gearName: "Saucony Endorphin Speed 3",
      syncedFrom: "Strava",
      routeName: "Sunset Intervals",
    },
    {
      id: "activity-long-run",
      title: "Sunday Long Run",
      type: "run",
      label: "Endurance",
      dateLabel: "Sunday · 7:15 AM",
      location: "River Trail Loop",
      distanceKm: 18.24,
      duration: "1:36:20",
      pace: "5:17/km",
      heartRate: 148,
      elevationM: 165,
      cadenceSpm: 169,
      calories: 1188,
      weather: "Sunny · 16 C",
      gearName: "Nike Pegasus 41",
      syncedFrom: "Stride",
      routeName: "River Trail Loop",
    },
    {
      id: "activity-recovery",
      title: "Easy Recovery Run",
      type: "run",
      label: "Recovery",
      dateLabel: "Thursday · 6:00 AM",
      location: "Neighborhood South",
      distanceKm: 6.02,
      duration: "33:10",
      pace: "5:31/km",
      heartRate: 138,
      elevationM: 32,
      calories: 352,
      gearName: "Nike Pegasus 41",
      syncedFrom: "Stride",
      routeName: "Neighborhood South",
    },
    {
      id: "activity-recovery-walk",
      title: "Evening Recovery Walk",
      type: "walk",
      label: "Recovery",
      dateLabel: "Wednesday · 7:20 PM",
      location: "Lakeside Park",
      distanceKm: 3.1,
      duration: "32:48",
      pace: "10:35/km",
      elevationM: 18,
      weather: "Cloudy · 17 C",
      syncedFrom: "Stride",
    },
    {
      id: "activity-commute-ride",
      title: "Commute Spin",
      type: "cycling",
      label: "Cross-train",
      dateLabel: "Tuesday · 8:05 AM",
      location: "City Loop",
      distanceKm: 14.8,
      duration: "42:12",
      pace: "2:51/km",
      heartRate: 129,
      weather: "Windy · 15 C",
      syncedFrom: "Strava",
    },
  ],
};

dashboardFixture.recentActivities = activitiesFixture.activities.slice(0, 3);

export const activityDetailsFixture: Record<string, ActivityDetail> = {
  "activity-intervals": {
    ...activitiesFixture.activities[0],
    splits: [
      { kilometer: "1", pace: "5:18", heartRate: 149 },
      { kilometer: "2", pace: "4:58", heartRate: 156 },
      { kilometer: "3", pace: "4:32", heartRate: 164 },
      { kilometer: "4", pace: "4:27", heartRate: 168 },
      { kilometer: "5", pace: "4:48", heartRate: 166 },
    ],
    routePreviewPath:
      "M10 130 C40 98,72 110,106 84 S182 46,224 58 S296 114,330 74",
    aiPrompt: "Why were the middle reps stronger than the final rep?",
  },
  "activity-long-run": {
    ...activitiesFixture.activities[1],
    splits: [
      { kilometer: "1", pace: "5:24", heartRate: 139 },
      { kilometer: "5", pace: "5:18", heartRate: 145 },
      { kilometer: "10", pace: "5:15", heartRate: 149 },
      { kilometer: "15", pace: "5:12", heartRate: 152 },
      { kilometer: "18", pace: "5:06", heartRate: 154 },
    ],
    routePreviewPath:
      "M16 112 C38 100,66 58,108 64 S188 118,226 90 S278 36,322 54",
    aiPrompt: "Summarize my endurance trend from this long run.",
  },
  "activity-recovery": {
    ...activitiesFixture.activities[2],
    splits: [
      { kilometer: "1", pace: "5:40", heartRate: 132 },
      { kilometer: "2", pace: "5:33", heartRate: 136 },
      { kilometer: "3", pace: "5:30", heartRate: 138 },
      { kilometer: "4", pace: "5:28" },
      { kilometer: "5", pace: "5:26" },
    ],
    aiPrompt: "Did I keep this recovery run easy enough?",
  },
  "activity-recovery-walk": {
    ...activitiesFixture.activities[3],
    splits: [
      { kilometer: "1", pace: "10:20" },
      { kilometer: "2", pace: "10:41" },
      { kilometer: "3", pace: "10:44" },
    ],
    aiPrompt: "How can walking support my recovery week?",
  },
  "activity-commute-ride": {
    ...activitiesFixture.activities[4],
    splits: [
      { kilometer: "5", pace: "2:49", heartRate: 126 },
      { kilometer: "10", pace: "2:52", heartRate: 129 },
      { kilometer: "14", pace: "2:54", heartRate: 131 },
    ],
    routePreviewPath:
      "M20 120 C62 108,88 88,122 94 S182 132,214 98 S286 40,326 68",
    aiPrompt: "Should this ride count toward recovery or fitness?",
  },
};

export const gearFixture: GearData = {
  metrics: [
    {
      label: "Active shoes",
      value: "3",
      detail: "Current weekly rotation",
      icon: "steps",
      tone: "primary",
    },
    {
      label: "Logged distance",
      value: "1,142 km",
      detail: "Across all active gear",
      icon: "straighten",
      tone: "accent",
    },
  ],
  gear: [
    {
      id: "gear-pegasus",
      type: "running-shoes",
      categoryLabel: "Running shoes",
      brand: "Nike",
      model: "Pegasus 41",
      name: "Nike Pegasus 41",
      mileageKm: 487,
      targetMileageKm: 700,
      statusLabel: "Approaching replacement",
      notes: "Daily trainer for road mileage and steady long runs.",
    },
    {
      id: "gear-saucony",
      type: "running-shoes",
      categoryLabel: "Running shoes",
      brand: "Saucony",
      model: "Endorphin Speed 3",
      name: "Saucony Endorphin Speed 3",
      mileageKm: 182,
      targetMileageKm: 600,
      statusLabel: "Healthy foam condition",
      notes: "Reserved for threshold work and race-pace sessions.",
    },
    {
      id: "gear-asics",
      type: "running-shoes",
      categoryLabel: "Running shoes",
      brand: "Asics",
      model: "Gel-Nimbus 26",
      name: "Asics Gel-Nimbus 26",
      mileageKm: 94,
      targetMileageKm: 800,
      statusLabel: "Fresh rotation slot",
      notes: "Recovery option with high cushioning for easy days.",
    },
    {
      id: "gear-watch",
      type: "watch",
      categoryLabel: "Watches",
      brand: "Garmin",
      model: "Forerunner 965",
      name: "Garmin Forerunner 965",
      mileageKm: 0,
      targetMileageKm: 0,
      statusLabel: "Connected",
      notes: "Primary watch for GPS, HR, and structured workouts.",
    },
  ],
};

export const goalsFixture: GoalsData = {
  metrics: [
    {
      label: "Active goals",
      value: "3",
      detail: "Race, volume, consistency",
      icon: "flag",
      tone: "primary",
    },
    {
      label: "Completed",
      value: "4",
      detail: "Recent verified milestones",
      icon: "military_tech",
      tone: "accent",
    },
  ],
  goals: [
    dashboardFixture.activeGoal,
    {
      id: "goal-monthly-sep",
      type: "Monthly Distance",
      title: "September mileage",
      targetLabel: "120 km target",
      currentLabel: "84.2 km completed",
      progressPercent: 70,
      remainingLabel: "35.8 km remaining",
      targetDate: "Sep 30",
      status: "active",
    },
    {
      id: "goal-run-count",
      type: "Number of Runs",
      title: "Run 16 times this month",
      targetLabel: "16 runs",
      currentLabel: "11 runs logged",
      progressPercent: 69,
      remainingLabel: "5 runs remaining",
      targetDate: "Sep 30",
      status: "active",
    },
    {
      id: "goal-sub-22",
      type: "5K",
      title: "Sub-22 minute 5K",
      targetLabel: "21:59 target",
      currentLabel: "21:44 official time",
      progressPercent: 100,
      remainingLabel: "Completed with a 32s PB",
      targetDate: "Aug 14",
      status: "completed",
    },
    {
      id: "goal-100-aug",
      type: "Monthly Distance",
      title: "Run 100 km in August",
      targetLabel: "100 km target",
      currentLabel: "104.2 km completed",
      progressPercent: 100,
      remainingLabel: "Completed at 104%",
      targetDate: "Aug 31",
      status: "completed",
    },
  ],
};

export const profileFixture: ProfileData = {
  name: "Ram Subramanian",
  email: "ram@stride.app",
  initials: "RS",
  stats: [
    {
      label: "Total distance",
      value: "1,842 km",
      detail: "Past 12 months",
      icon: "straighten",
      tone: "primary",
    },
    {
      label: "Total runs",
      value: "164",
      detail: "Stride-owned history",
      icon: "directions_run",
      tone: "accent",
    },
    {
      label: "Longest run",
      value: "24.1 km",
      detail: "Spring build peak",
      icon: "timeline",
      tone: "warning",
    },
  ],
  profileItems: [
    { label: "Preferred distance", value: "10K to Half Marathon" },
    { label: "Experience level", value: "Intermediate" },
    { label: "Weekly mileage", value: "35 to 45 km" },
    { label: "Typical running days", value: "Mon Tue Thu Sat" },
    { label: "Preferred pace", value: "Easy at 5:30/km" },
    { label: "Running goals", value: "Half marathon and consistent volume" },
  ],
  settings: [
    { label: "Notifications", value: "Workout reminders on", icon: "notifications" },
    { label: "Appearance", value: "Light system", icon: "palette" },
    { label: "Units", value: "Metric", icon: "straighten" },
    { label: "Privacy", value: "Stride-only history", icon: "shield" },
    { label: "Connected accounts", value: "Strava connected", icon: "hub" },
    { label: "AI Buddy", value: "Optional insight surface", icon: "neurology" },
    { label: "Account", value: "Manage email and sessions", icon: "person" },
  ],
};

export const stravaViewsFixture: Record<string, StravaConnectionData> = {
  connected: {
    status: "connected",
    lastSynced: "Today, 8:32 AM",
    summary: "Connect Strava to import running activities into Stride.",
    importWindow: "Latest 30 days imported through Stride API",
    coverage: "Connected with recent-window coverage",
  },
  syncing: {
    status: "syncing",
    lastSynced: "Sync in progress",
    summary: "Syncing your activities through the Stride backend worker.",
    importWindow: "Recent activity pages and detail fetch in progress",
    coverage: "Background worker owns retries and quotas",
  },
  error: {
    status: "error",
    lastSynced: "Yesterday, 6:14 PM",
    summary: "Unable to sync activities. Reconnect or retry from the Stride API.",
    importWindow: "Last known data remains available in Stride",
    coverage: "Profile, gear, and goals stay available without Strava",
  },
};

export const aiFixture: AIData = {
  title: "AI Buddy",
  subtitle: "Your personal running companion",
  suggestions: [
    "How was my last run?",
    "Am I improving?",
    "Why was my pace slower this week?",
    "Help me prepare for my 10K.",
    "What should I focus on next?",
  ],
};

export const goalTypeOptions: GoalType[] = [
  "5K",
  "10K",
  "Half Marathon",
  "Marathon",
  "Weekly Distance",
  "Monthly Distance",
  "Number of Runs",
  "Target Pace",
  "Custom Goal",
];

export const defaultGoalForm: GoalFormInput = {
  type: "10K",
  title: "10K race target",
  targetDistanceKm: "10",
  targetDate: "2026-10-20",
  targetPace: "5:00/km",
  targetTime: "50:00",
  frequency: "Weekly check-ins",
};