import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useActivities } from "../hooks/use-stride-data";
import { PageHeader, PrimaryButton, Screen, appPalette } from "../ui/stride-ui";
import type { ActivitySummary } from "../types/stride";

export function ActivitiesScreen({ onOpenDetails, onAddActivity }: { onOpenDetails: (activity: ActivitySummary) => void; onAddActivity: () => void }) {
  const { data } = useActivities();
  const [filter, setFilter] = useState("Run");
  const [query, setQuery] = useState("");
  const visibleActivities = (data ?? []).filter((activity) => (filter === "All" || activity.category === "RUN") && activity.title.toLowerCase().includes(query.toLowerCase()));

  return (
    <Screen>
      <PageHeader title="Activities" />
      <View><View style={styles.titleRow}><Text style={styles.heading}>Activities</Text><Text style={styles.live}>LIVE LOG</Text></View><Text style={styles.month}><Ionicons name="calendar-outline" size={15} color={appPalette.primary} /> September 2026 · <Text style={styles.primary}>114.8 KM</Text> · 14 Runs</Text></View>
      <Pressable style={styles.sync}><Ionicons name="flash" size={21} color={appPalette.primary} /><View style={{ flex: 1 }}><Text style={styles.syncTitle}>STRAVA SYNCED <Text style={styles.muted}>• 15 min ago</Text></Text><Text style={styles.muted}>2 new activities imported automatically</Text></View><Ionicons name="sync-outline" size={20} color={appPalette.primary} /></Pressable>
      <View style={styles.search}><Ionicons name="search-outline" size={22} color={appPalette.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search route, title, shoe, location..." placeholderTextColor={appPalette.muted} style={styles.input} /></View>
      <View style={styles.filters}>{["All", "Run", "Trail Run", "Recovery"].map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.filterActive]}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item.toUpperCase()} {item === "All" ? "(17)" : item === "Run" ? "(12)" : "(2)"}</Text></Pressable>)}</View>
      {visibleActivities.map((activity, index) => <View key={activity.id} style={styles.group}><View style={styles.dateRow}><Text style={styles.date}><Text style={styles.dateDot}>●</Text> {index === 0 ? "Yesterday" : index === 1 ? "Sunday" : "Thursday"} <Text style={styles.dateSmall}>· SEP {index === 0 ? "18" : index === 1 ? "15" : "12"}</Text></Text><Text style={styles.muted}>{index === 0 ? "1 Session" : index === 1 ? "Long Run Target" : "Recovery"}</Text></View><Pressable onPress={() => onOpenDetails(activity)} style={styles.activityCard}><View style={styles.activityTop}><View style={styles.activityIcon}><Ionicons name={index === 1 ? "trail-sign-outline" : "speedometer-outline"} size={25} color={index === 1 ? appPalette.accent : appPalette.primary} /></View><View style={{ flex: 1 }}><Text numberOfLines={1} style={styles.activityTitle}>{activity.title}</Text><Text style={styles.category}>{activity.category} <Text style={styles.muted}>· {activity.location} · {activity.dateLabel}</Text></Text></View>{index === 0 ? <Text style={styles.imported}>STRAVA</Text> : null}</View><View style={styles.activityMetrics}><Data label="DISTANCE" value={`${activity.distanceKm}`} unit="km" /><Data label="DURATION" value={activity.durationLabel} /><Data label="AVG PACE" value={activity.paceLabel.replace(" /km", "")} unit="/km" /></View><View style={styles.activityFoot}><Text style={styles.muted}>♡ {activity.heartRate} bpm  △ {activity.elevationGainM} m gain</Text><Text style={styles.muted}>{activity.gearName}</Text></View></Pressable></View>)}
      <PrimaryButton label="Log manual run" onPress={onAddActivity} />
    </Screen>
  );
}

function Data({ label, value, unit }: { label: string; value: string; unit?: string }) { return <View><Text style={styles.dataLabel}>{label}</Text><Text style={styles.dataValue}>{value}<Text style={styles.unit}>{unit}</Text></Text></View>; }
const styles = StyleSheet.create({ titleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, heading: { color: appPalette.text, fontSize: 29, fontWeight: "700" }, live: { color: appPalette.primary, backgroundColor: "#FFF0EB", borderRadius: 999, fontSize: 10, fontWeight: "700", letterSpacing: 1, paddingHorizontal: 8, paddingVertical: 5 }, month: { color: appPalette.muted, fontSize: 15, marginTop: 5 }, primary: { color: appPalette.primary, fontWeight: "700" }, sync: { alignItems: "center", backgroundColor: appPalette.surface, borderRadius: 16, flexDirection: "row", gap: 10, padding: 12 }, syncTitle: { color: appPalette.text, fontSize: 11, fontWeight: "700", letterSpacing: 1 }, muted: { color: appPalette.muted, fontSize: 13 }, search: { alignItems: "center", backgroundColor: appPalette.surface, borderRadius: 14, flexDirection: "row", gap: 9, paddingHorizontal: 14 }, input: { color: appPalette.text, flex: 1, fontSize: 16, paddingVertical: 13 }, filters: { flexDirection: "row", gap: 7 }, filter: { backgroundColor: appPalette.surface, borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7 }, filterActive: { backgroundColor: appPalette.text }, filterText: { color: appPalette.muted, fontSize: 10, fontWeight: "700", letterSpacing: .8 }, filterTextActive: { color: "#FFFFFF" }, group: { gap: 8 }, dateRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, date: { color: appPalette.text, fontSize: 21, fontWeight: "700" }, dateDot: { color: appPalette.primary, fontSize: 12 }, dateSmall: { color: appPalette.muted, fontSize: 11, letterSpacing: 1 }, activityCard: { backgroundColor: appPalette.surface, borderRadius: 18, overflow: "hidden", paddingTop: 15 }, activityTop: { alignItems: "center", flexDirection: "row", gap: 11, paddingHorizontal: 14 }, activityIcon: { alignItems: "center", backgroundColor: appPalette.surfaceMuted, borderRadius: 12, height: 49, justifyContent: "center", width: 49 }, activityTitle: { color: appPalette.text, fontSize: 21, fontWeight: "600" }, category: { color: appPalette.primary, fontSize: 11, fontWeight: "700", marginTop: 4, letterSpacing: .7 }, imported: { color: appPalette.primary, fontSize: 11, fontWeight: "700" }, activityMetrics: { backgroundColor: appPalette.surfaceMuted, borderRadius: 13, flexDirection: "row", justifyContent: "space-between", margin: 14, padding: 12 }, dataLabel: { color: appPalette.muted, fontSize: 10, fontWeight: "700", letterSpacing: .7 }, dataValue: { color: appPalette.text, fontSize: 22, fontWeight: "700", marginTop: 4 }, unit: { color: appPalette.muted, fontSize: 11, fontWeight: "400" }, activityFoot: { borderTopColor: appPalette.surfaceMuted, borderTopWidth: 1, gap: 5, padding: 12 } });
